DROP TABLE GARANTIA;
DROP TABLE MANUTENCAO;
DROP TABLE EMPRESTIMO;
DROP TABLE ATIVO;
DROP TABLE STATUS;
DROP TABLE LOGIN;
DROP TABLE USUARIOS_SISTEMA;
DROP TABLE PERFIL;
DROP TABLE FUNCIONARIO;
DROP TABLE CATEGORIA;

CREATE TABLE PERFIL (
ID int NOT NULL AUTO_INCREMENT,
DESCRICAO varchar (30) NOT NULL,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRIACAO DATETIME,
DT_MODIFICACAO DATETIME,
PRIMARY KEY (ID)
);

CREATE TABLE FUNCIONARIO (
ID int NOT NULL AUTO_INCREMENT,
NOME varchar (30) NOT NULL,
CPF varchar (15),
CNPJ varchar (20),
CARGO varchar (30) NOT NULL,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRIACAO DATETIME,
DT_MODIFICACAO DATETIME,
PRIMARY KEY (ID)
);

CREATE TABLE USUARIOS_SISTEMA (
ID int NOT NULL AUTO_INCREMENT,
USERNAME varchar (15) NOT NULL,
ID_PERFIL int NOT NULL,
SENHA varchar (30) NOT NULL,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRIACAO DATETIME,
DT_MODIFICACAO DATETIME,
PRIMARY KEY (ID)
);

CREATE TABLE LOGIN ( 
ID int NOT NULL,
DT_ACESSO DATETIME NOT NULL
);

CREATE TABLE STATUS (
ID int NOT NULL AUTO_INCREMENT,
DESCRICAO varchar (30) NOT NULL,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRIACAO DATETIME,
DT_MODIFICACAO DATETIME,
PRIMARY KEY (ID)
);

CREATE TABLE ATIVO (
ID int NOT NULL AUTO_INCREMENT,
DESCRICAO varchar (30),
FABRICANTE varchar (30),
DT_COMPRA DATE NOT NULL,
VL_COMPRA int NOT NULL,
VL_DEPRECIADO int NOT NULL,
ID_STATUS int NOT NULL,
OBSERVACAO varchar (50),
ID_CATEGORIA int NOT NULL,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRIACAO DATETIME,
DT_MODIFICACAO DATETIME,
PRIMARY KEY (ID)
);

CREATE TABLE EMPRESTIMO (
ID_FUNCIONARIO int NOT NULL AUTO_INCREMENT,
ID_ATIVO int NOT NULL,
DT_EMPRESTIMO DATE NOT NULL,
DT_DEVOLUCAO DATE,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRIACAO DATETIME,
DT_MODIFICACAO DATETIME,
PRIMARY KEY (ID_FUNCIONARIO, ID_ATIVO)
);

CREATE TABLE MANUTENCAO (
ID int NOT NULL AUTO_INCREMENT,
ID_ATIVO int NOT NULL,
DESCRICAO varchar (30) NOT NULL,
DT_ENTRADA DATE NOT NULL,
DT_CONSERTO DATE,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRIACAO DATETIME,
DT_MODIFICACAO DATETIME,
PRIMARY KEY (ID)
);

CREATE TABLE GARANTIA (
ID int NOT NULL AUTO_INCREMENT,
ID_ATIVO int NOT NULL,
FORNECEDOR varchar (30) NOT NULL,
CONTATO varchar (30) NOT NULL,
CRIADO_POR int,
DT_VALIDADE DATETIME NOT NULL,
MODIFICADO_POR int,
DT_CRIACAO DATETIME,
DT_MODIFICACAO DATETIME,
PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA (
ID int NOT NULL AUTO_INCREMENT,
DESCRICAO varchar (30) NOT NULL,
PRCNT_DEPRE int (3)  NOT NULL,
DT_DEPRECIACAO DATETIME NOT NULL,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRIACAO DATETIME,
DT_MODIFICACAO DATETIME,
PRIMARY KEY (ID)
);


ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNC_C FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNC_M FOREIGN KEY (MODIFICADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE GARANTIA ADD CONSTRAINT FK_GARANTIA_C FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE GARANTIA ADD CONSTRAINT FK_GARANTIA_M FOREIGN KEY (MODIFICADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE GARANTIA ADD CONSTRAINT FK_GARANTIA_A FOREIGN KEY (ID_ATIVO) REFERENCES ATIVO(ID);
ALTER TABLE MANUTENCAO ADD CONSTRAINT FK_MANUTENCAO_C FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE MANUTENCAO ADD CONSTRAINT FK_MANUTENCAO_M FOREIGN KEY (MODIFICADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE MANUTENCAO ADD CONSTRAINT FK_MANUTENCAO_A FOREIGN KEY (ID_ATIVO) REFERENCES ATIVO(ID);
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_C FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_M FOREIGN KEY (MODIFICADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_A FOREIGN KEY (ID_ATIVO) REFERENCES ATIVO(ID);
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_F FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID);
ALTER TABLE ATIVO ADD CONSTRAINT FK_ATIVO_C FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE ATIVO ADD CONSTRAINT FK_ATIVO_M FOREIGN KEY (MODIFICADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE ATIVO ADD CONSTRAINT FK_ATIVO_S FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID);
ALTER TABLE LOGIN ADD CONSTRAINT FK_LOGIN_U FOREIGN KEY (ID) REFERENCES USUARIOS_SISTEMA (ID);
ALTER TABLE USUARIOS_SISTEMA ADD CONSTRAINT FK_USR_SIS_F FOREIGN KEY (ID) REFERENCES FUNCIONARIO(ID);
ALTER TABLE USUARIOS_SISTEMA ADD CONSTRAINT FK_USR_SIS_P FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID);
ALTER TABLE GARANTIA ADD CONSTRAINT FK_GAR_C FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE GARANTIA ADD CONSTRAINT FK_GAR_M FOREIGN KEY (MODIFICADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE CATEGORIA ADD CONSTRAINT FK_CAT_C FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE CATEGORIA ADD CONSTRAINT FK_CAT_M FOREIGN KEY (MODIFICADO_POR) REFERENCES USUARIOS_SISTEMA(ID);
ALTER TABLE ATIVO ADD CONSTRAINT FK_ATVO_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID);



alter table FUNCIONARIO DROP FOREIGN KEY FK_FUNC_C;
alter table FUNCIONARIO DROP FOREIGN KEY FK_FUNC_M;
alter table GARANTIA DROP FOREIGN KEY FK_GARANTIA_C;
alter table GARANTIA DROP FOREIGN KEY FK_GARANTIA_M;
alter table GARANTIA DROP FOREIGN KEY FK_GARANTIA_A;
alter table MANUTENCAO DROP FOREIGN KEY FK_MANUTENCAO_C;
alter table MANUTENCAO DROP FOREIGN KEY FK_MANUTENCAO_M;
alter table MANUTENCAO DROP FOREIGN KEY FK_MANUTENCAO_A;
alter table EMPRESTIMO DROP FOREIGN KEY FK_EMPRESTIMO_C;
alter table EMPRESTIMO DROP FOREIGN KEY FK_EMPRESTIMO_M;
alter table EMPRESTIMO DROP FOREIGN KEY FK_EMPRESTIMO_A;
alter table EMPRESTIMO DROP FOREIGN KEY FK_EMPRESTIMO_F;
alter table ATIVO DROP FOREIGN KEY FK_ATIVO_C;
alter table ATIVO DROP FOREIGN KEY FK_ATIVO_M;
alter table ATIVO DROP FOREIGN KEY FK_ATIVO_S;
alter table ATIVO DROP FOREIGN KEY FK_ATVO_CAT;
alter table LOGIN DROP FOREIGN KEY FK_LOGIN_U;
alter table USUARIOS_SISTEMA DROP FOREIGN KEY FK_USR_SIS_F;
alter table USUARIOS_SISTEMA DROP FOREIGN KEY FK_USR_SIS_P;
alter table GARANTIA DROP FOREIGN KEY FK_GAR_C;
alter table GARANTIA DROP FOREIGN KEY FK_GAR_M;
alter table CATEGORIA DROP FOREIGN KEY FK_CAT_C;
alter table CATEGORIA DROP FOREIGN KEY FK_CAT_M;



truncate table FUNCIONARIO;
truncate table GARANTIA; 
truncate table MANUTENCAO;
truncate table EMPRESTIMO;
truncate table ATIVO;
truncate table LOGIN;
truncate table USUARIOS_SISTEMA;
truncate table CATEGORIA;
truncate table STATUS;
truncate table PERFIL;